/*

This template has been autogenerated by gradle on Fri Mar 27 14:02:13 EDT 2020

Do not edit this file.  All changes will be deleted the next time test resources are generated.
*/

package gov.dhs.tsa.tas.serenity;

import gov.dhs.tsa.tas.serenity.framework.CustomizedCucumberWithSerenity;
import org.junit.runner.RunWith;
import cucumber.api.CucumberOptions;
import cucumber.api.SnippetType;

@RunWith(CustomizedCucumberWithSerenity.class)
@CucumberOptions(
features={"C:/Users/soraj.nabangchang/Documents/SerenityAFS/src/test/resources/autogenerated/feature0"}, 
snippets=SnippetType.CAMELCASE, 
strict=true, 
plugin = {"gov.dhs.tsa.tas.serenity.framework.CustomFormatter"},
monochrome=true
)
public class CucumberTestSuite0 {
}  
 