/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'joe.chang' at '4/3/17 9:58 AM' with Gradle 2.9
 *
 * @author joe.chang, @date 4/3/17 9:58 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
