/*

This template has been autogenerated by gradle on Mon Jun 08 13:32:11 EDT 2020

Do not edit this file.  All changes will be deleted the next time test resources are generated.
*/

package gov.dhs.tsa.rh.serenity;

import gov.dhs.tsa.rh.serenity.framework.CustomizedCucumberWithSerenity;
import org.junit.runner.RunWith;
import cucumber.api.CucumberOptions;
import cucumber.api.SnippetType;

@RunWith(CustomizedCucumberWithSerenity.class)
@CucumberOptions(
features={"C:/Users/soraj.nabangchang/Documents/SerenityRH/TSA-RH/src/test/resources/autogenerated/feature0"}, 
snippets=SnippetType.CAMELCASE, 
strict=true, 
plugin = {"gov.dhs.tsa.rh.serenity.framework.CustomFormatter"},
monochrome=true
)
public class CucumberTestSuite0 {
}  
 